### ISSUE TITLE
Increase desire counts, generally?

### ISSUE THREAD

**Issue by makoConstruct** [makoConstruct/P1#11]
Optimization Process has been reporting that they'll frequently get into situations where their desires are negating each other, or where they have no way to pursue them at all. This happens especially often now that killing goals require the killer to be the holder of the goal.

This could be addressed quickly by just increasing the number of goals players have. This could eventually make conflicts too vague and hard to identify, but one extra wouldn't hurt too much, I think?

This is also addressed by the proposal to seek new abilities over time in [the infinite variant from the ideas bag](https://dreamshrine.org/OW.1/manual.html#developer-corner) (deserves its own issue).

**Comment by speezepearson** [comment]
> now that killing goals require the killer to be the holder of the goal

From your wording, it sounds like the killing goals used to _not_ require this -- why the change?

Variations that've floated through my head:
- "4 points per dead agent" -- just drop the requirement that you kill them. You've probably discarded this.
- "4 points per agent you eat" (wording needs work) -- I'm thinking that, when an agent dies, the killer gets the "corpse," and can eat it themself or trade it to somebody with A Terrible Hunger to be consumed.

**Comment by makoConstruct** [comment]
Hmm there's no reason we couldn't implement corpse trading mechanics, where whenever you kill, you receive the corpse, and when you're in the same land as another agent, you can give them the corpse.

We could also allow leaving corpses on the board, laying sideways. Unfortunately a lot of ad-hoc pieces that people tend to use can't lay sideways, but enough of the official pieces can.

**Comment by makoConstruct** [comment]
> From your wording, it sounds like the killing goals used to not require this -- why the change?

Kill goals were just too surreal, and in that way too mean-spirited, as it would mean that there's a character who just abstractly benefits from suffering, which I think is one of the things I want to argue isn't really prevalent in the real world, that the reason people so often hurt each other is incidental to their actual goals, and negotiable (EG, they do it because they are scared, they do it because they are hungry).

By the way, have you noticed that they're still quite surreal in the way that people are indifferent to their own deaths, so they may decide to pledge their flesh to another player. Actually, reflecting on that, I think that's just cool. We have similar phenomena in human society, most directly, meat farming. The well treated (grass-fed) cow, if it understood it all in totality, may just choose to accept the deal.

**Comment by speezepearson** [comment]
> By the way, have you noticed that they're still quite surreal in the way that people are indifferent to their own deaths, so they may decide to pledge their flesh to another player.

Ha! I hadn't experienced that. (Though, in the last round I played, the person with by far the most points was the person I double-murdered on, like, turn 2. The board just... turned out right for them. So, yeah, I'd noticed that having surviving agents was merely a nice-to-have.)

**Comment by speezepearson** [comment]
This issue is closed as of the update you just posted on Element, I think!

**Comment by makoConstruct** [comment]
tentatively closed until the next time I see a person draw both the forest and field desire
